# Superstore Sales Analysis using Pandas

## Level 1: Data Understanding

In [1]:
import pandas as pd
df=pd.read_csv("Superstore.csv")

### Q1. Display the number of rows and columns in the dataset.

In [2]:
Shape=df.shape
print("Shape:",Shape)

Shape: (10194, 21)

### Q2. Display all column names.

In [3]:
columns_name=df.columns
print("Columns:",columns_name)

Columns: Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City',
       'State/Province', 'Postal Code', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='str')

### Q3. Display basic information about the dataset.

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  str
 2   Order Date      10194 non-null  str
 3   Ship Date       10194 non-null  str
 4   Ship Mode       10194 non-null  str
 5   Customer ID     10194 non-null  str
 6   Customer Name   10194 non-null  str
 7   Segment         10194 non-null  str
 8   Country/Region  10194 non-null  str
 9   City            10194 non-null  str
 10  State/Province  10194 non-null  str
 11  Postal Code     10194 non-null  str
 12  Region          10194 non-null  str
 13  Product ID      10194 non-null  str
 14  Category        10194 non-null  str
 15  Sub-Category    10194 non-null  str
 16  Product Name    10194 non-null  str
 17  Sales           10194 non-null  float64
 18  Quantity        10194 non-null  int64
 19  Discount        10194 non-null  float64
 20  Profit          10194 non-null  float64
dtypes: float64(3), int64(2), str(16)
memory usage: 1.6 MB

### Q4. Display the statistical summary of numerical columns.

In [5]:
df.describe()

             Row ID         Sales      Quantity      Discount        Profit
count  10194.000000  10194.000000  10194.000000  10194.000000  10194.000000
mean    5097.500000    228.225854      3.791838      0.155385     28.673417
std     2942.898656    619.906839      2.228317      0.206249    232.465115
min        1.000000      0.444000      1.000000      0.000000  -6599.978000
25%     2549.250000     17.220000      2.000000      0.000000      1.760800
50%     5097.500000     53.910000      3.000000      0.200000      8.690000
75%     7645.750000    209.500000      5.000000      0.200000     29.297925
max    10194.000000  22638.480000     14.000000      0.800000   8399.976000

### Q5. Check for missing values in the dataset.

In [6]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
dtype: int64

### Q6. Check the data type of each column.

In [7]:
df.dtypes

Row ID              int64
Order ID              str
Order Date            str
Ship Date             str
Ship Mode             str
Customer ID           str
Customer Name         str
Segment               str
Country/Region        str
City                  str
State/Province        str
Postal Code           str
Region                str
Product ID            str
Category              str
Sub-Category          str
Product Name          str
Sales             float64
Quantity            int64
Discount          float64
Profit            float64
dtype: object

### Q7. Check the total number of duplicate rows.

In [8]:
duplicate_row=df.duplicated().sum()
print("Duplicated rows:",duplicate_row)

Duplicated rows: 0

### Q8. Find the total number of unique customers.

In [9]:
unique_customers = df["Customer Name"].nunique()

print("Total Unique Customers:", unique_customers)

Total Unique Customers: 800

### Q9 Convert 'Order Date' and 'Ship Date' Columns to DateTime Format.

In [10]:
df["Order Date"]=pd.to_datetime(df["Order Date"],errors="coerce")
df["Ship Date"]=pd.to_datetime(df["Ship Date"],errors="coerce")

# Level 2: Data Cleaning & Feature Engineering

### Q10. Fill Missing Values with Suitable Values.

In [11]:
df["Order Date"] = df["Order Date"].ffill()

In [12]:
df["Order Date"].isnull().sum()

np.int64(0)

In [13]:
df["Ship Date"]=df["Ship Date"].ffill()

In [14]:
df["Ship Date"].isnull().sum()

np.int64(0)

In [15]:
df["Postal Code"]=df["Postal Code"].fillna(df["Postal Code"].mode()[0])

In [16]:
df["Postal Code"].isnull().sum()

np.int64(0)

In [17]:
df["Customer Name"]=df["Customer Name"].str.title()

In [18]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

### Q11. Remove Extra Spaces from Product Names.

In [19]:
df["Product Name"]=df["Product Name"].str.strip()

### Q12. Create a new column 'Profit Status' (Profit / Loss).

In [20]:
df["Profit Status"]=df["Profit"].apply(lambda x:"Profit" if x>0 else("Loss" if x<0 else "No Profit Loss"))

### Q13. Round Off the Sales Values to Two Decimal Places.

In [21]:
df["Sales"]=df["Sales"].round(2)

### Q14. Create a new column named 'Discount Percentage'.

In [22]:
df["Discount Percentage"] = (df["Discount"] * 100).astype(int)

In [23]:
print(df["Discount Percentage"])

0        20
1        80
2        20
3        20
4        20
         ..
10189    20
10190    20
10191    20
10192     0
10193    20
Name: Discount Percentage, Length: 10194, dtype: int64

###  Q15. Extract Year, Month  Order Date.

In [24]:
df["Order Year"]=df["Order Date"].dt.year
df["Order Month"]=df["Order Date"].dt.month_name()
print(df["Order Year"])

0        2023
1        2023
2        2023
3        2023
4        2023
         ...
10189    2026
10190    2026
10191    2026
10192    2026
10193    2026
Name: Order Year, Length: 10194, dtype: int32

# Filtering & Sorting

### Q16. Display all records belonging to the Furniture category.

In [25]:
furniture=(df[df["Category"]=="Furniture"])
print(furniture)

       Row ID        Order ID Order Date  Ship Date       Ship Mode  \
5           6  US-2023-167199 2023-01-06 2023-01-10  Standard Class
14         15  US-2023-105417 2023-01-07 2023-01-12  Standard Class
18         19  US-2023-149020 2023-01-10 2023-01-15  Standard Class
20         21  US-2023-130092 2023-01-11 2023-01-14     First Class
21         22  US-2023-157147 2023-01-13 2023-01-18  Standard Class
...       ...             ...        ...        ...             ...
10175   10176  US-2026-146626 2026-12-29 2027-01-05  Standard Class
10176   10177  US-2026-130631 2026-12-29 2027-01-02  Standard Class
10183   10184  CA-2026-146626 2026-12-29 2027-01-05  Standard Class
10184   10185  CA-2026-141531 2026-12-29 2027-01-02  Standard Class
10186   10187  US-2026-143259 2026-12-30 2027-01-03  Standard Class

      Customer ID      Customer Name      Segment Country/Region  \
5        ME-17320      Maria Etezadi  Home Office  United States
14       VS-21820   Vivek Sundaresam     Consumer  United States
18       AJ-10780     Anthony Jacobs    Corporate  United States
20       SV-20365        Seth Vernon     Consumer  United States
21       BD-11605       Brian Dahlen     Consumer  United States
...           ...                ...          ...            ...
10175    BP-11185       Ben Peterman    Corporate  United States
10176    BS-11755      Bruce Stewart     Consumer  United States
10183    JP-11135     James Peterman    Corporate         Canada
10184    BG-18435       Bruce Galang     Consumer         Canada
10186    PO-18865  Patrick O'Donnell     Consumer  United States

                City  ... Sub-Category  \
5          Henderson  ...       Chairs
14        Huntsville  ...  Furnishings
18       Springfield  ...  Furnishings
20             Dover  ...  Furnishings
21     San Francisco  ...    Bookcases
...              ...  ...          ...
10175        Anaheim  ...  Furnishings
10176        Edmonds  ...  Furnishings
10183     St. John's  ...  Furnishings
10184    Quebec City  ...  Furnishings
10186  New York City  ...    Bookcases

                                            Product Name    Sales Quantity  \
5                Global Deluxe High-Back Manager's Chair  2573.82        9
14     Howard Miller 14-1/2" Diameter Chrome Round Wa...    76.73        3
18     Howard Miller 11-1/2" Diameter Ridgewood Wall ...    51.94        1
20       DAX Value U-Channel Document Frames, Easel Back     9.94        2
21         O'Sullivan Elevations Bookcase, Cherry Finish   334.00        3
...                                                  ...      ...      ...
10175                            Nu-Dell Executive Frame   101.12        8
10176            Hand-Finished Solid Wood Document Frame    68.46        2
10183                            Nu-Dell Executive Frame    99.12        8
10184            Hand-Finished Solid Wood Document Frame    68.46        2
10186  Bush Westfield Collection Bookcases, Fully Ass...   323.14        4

      Discount    Profit Profit Status  Discount Percentage  Order Year  \
5         0.00  746.4078        Profit                    0        2023
14        0.60  -53.7096          Loss                   60        2023
18        0.00   21.2954        Profit                    0        2023
20        0.00    3.0814        Profit                    0        2023
21        0.15    3.9294        Profit                   15        2023
...        ...       ...           ...                  ...         ...
10175     0.00   37.4144        Profit                    0        2026
10176     0.00   20.5380        Profit                    0        2026
10183     0.00   35.4144        Profit                    0        2026
10184     0.00   20.5380        Profit                    0        2026
10186     0.20   12.1176        Profit                   20        2026

       Order Month
5          January
14         January
18         January
20         January
21         January
...            ...
10175     December
10176     December
10183     December
10184     December
10186     December

[2201 rows x 25 columns]

### Q17. Display all records belonging to the Technology category.

In [26]:
Technology=(df[df["Category"]=="Technology"])
print(Technology)

       Row ID        Order ID Order Date  Ship Date       Ship Mode  \
12         13  US-2023-167199 2023-01-06 2023-01-10  Standard Class
13         14  US-2023-167199 2023-01-06 2023-01-10  Standard Class
17         18  US-2023-135405 2023-01-09 2023-01-13  Standard Class
31         32  US-2023-162775 2023-01-13 2023-01-15    Second Class
33         34  US-2023-103366 2023-01-15 2023-01-17     First Class
...       ...             ...        ...        ...             ...
10145   10146  US-2026-114055 2026-12-25 2026-12-29    Second Class
10151   10152  US-2026-134404 2026-12-27 2026-12-27        Same Day
10170   10171  US-2026-164826 2026-12-28 2027-01-04  Standard Class
10182   10183  US-2026-118885 2026-12-29 2027-01-02  Standard Class
10192   10193  US-2026-143259 2026-12-30 2027-01-03  Standard Class

      Customer ID      Customer Name      Segment Country/Region  \
12       ME-17320      Maria Etezadi  Home Office  United States
13       ME-17320      Maria Etezadi  Home Office  United States
17       MS-17830      Melanie Seite     Consumer  United States
31       CS-12250    Chris Selesnick    Corporate  United States
33       EH-13990      Erica Hackney     Consumer  United States
...           ...                ...          ...            ...
10145    MH-18115     Mick Hernandez  Home Office  United States
10151    DR-12880    Dan Reichenbach    Corporate  United States
10170    JF-15415  Jennifer Ferguson     Consumer  United States
10182    JG-15160       James Galang     Consumer  United States
10192    PO-18865  Patrick O'Donnell     Consumer  United States

                City  ... Sub-Category  \
12         Henderson  ...       Phones
13         Henderson  ...       Phones
17            Laredo  ...  Accessories
31      Bossier City  ...  Accessories
33           Roswell  ...  Accessories
...              ...  ...          ...
10145     Huntsville  ...       Phones
10151         Newark  ...       Phones
10170  New York City  ...       Phones
10182    Los Angeles  ...       Phones
10192  New York City  ...       Phones

                                            Product Name   Sales Quantity  \
12     Wireless Extenders zBoost YX545 SOHO Signal Bo...  755.96        4
13                                           GE 30524EE4  391.98        2
17                       Memorex Micro Travel Drive 8 GB   31.20        3
31       Plantronics S12 Corded Telephone Headset System  646.74        6
33     Logitech 910-002974 M325 Wireless Mouse for We...  149.95        5
...                                                  ...     ...      ...
10145                      AT&T 17929 Lendline Telephone   90.48        2
10151                             AT&T 1080 Corded phone  164.39        2
10170  Cush Cases Heavy Duty Rugged Cover Case for Sa...   14.85        3
10182                                   Adtran 1202752G1  302.38        3
10192                          Gear Head AU3700S Headset   90.93        7

      Discount    Profit Profit Status  Discount Percentage  Order Year  \
12         0.0  204.1092        Profit                    0        2023
13         0.0  113.6742        Profit                    0        2023
17         0.2    9.7500        Profit                   20        2023
31         0.0  258.6960        Profit                    0        2023
33         0.0   65.9780        Profit                    0        2023
...        ...       ...           ...                  ...         ...
10145      0.0   23.5248        Profit                    0        2026
10151      0.4  -35.6174          Loss                   40        2026
10170      0.0    4.0095        Profit                    0        2026
10182      0.2   22.6782        Profit                   20        2026
10192      0.0    2.7279        Profit                    0        2026

       Order Month
12         January
13         January
17         January
31         January
33         January
...            ...
10145     December
10151     December
10170     December
10182     December
10192     December

[1865 rows x 25 columns]

### Q18. Display all records where Sales are greater than 1000.

In [27]:
High_sales=df[df["Sales"]>1000]
print(High_sales)

       Row ID        Order ID Order Date  Ship Date       Ship Mode  \
5           6  US-2023-167199 2023-01-06 2023-01-10  Standard Class
30         31  US-2023-157147 2023-01-13 2023-01-18  Standard Class
43         44  US-2023-147627 2023-01-20 2023-01-26  Standard Class
102       103  US-2023-127614 2023-02-11 2023-02-15  Standard Class
181       182  US-2023-125521 2023-03-14 2023-03-19  Standard Class
...       ...             ...        ...        ...             ...
10059   10060  US-2026-138380 2026-12-21 2026-12-25  Standard Class
10066   10067  US-2026-120376 2026-12-22 2026-12-25     First Class
10120   10121  US-2026-147956 2026-12-24 2026-12-31  Standard Class
10121   10122  US-2026-145219 2026-12-24 2026-12-25     First Class
10172   10173  US-2026-158526 2026-12-29 2027-01-01    Second Class

      Customer ID       Customer Name      Segment Country/Region  \
5        ME-17320       Maria Etezadi  Home Office  United States
30       BD-11605        Brian Dahlen     Consumer  United States
43       HL-15040        Hunter Lopez     Consumer  United States
102      NF-18385    Natalie Fritzler     Consumer  United States
181      CK-12325  Christine Kargatis  Home Office  United States
...           ...                 ...          ...            ...
10059    YS-21880       Yana Sorensen    Corporate  United States
10066    TP-21130    Theone Pippenger     Consumer  United States
10120    AH-10210          Alan Hwang     Consumer  United States
10121    RM-19675       Robert Marley  Home Office  United States
10172    KH-16360    Katherine Hughes     Consumer  United States

                City  ... Sub-Category  \
5          Henderson  ...       Chairs
30     San Francisco  ...      Storage
43         Jonesboro  ...       Chairs
102       Chesapeake  ...       Tables
181       Chesapeake  ...       Chairs
...              ...  ...          ...
10059        Oakland  ...      Storage
10066        Detroit  ...       Chairs
10120        Seattle  ...      Storage
10121    Los Angeles  ...      Copiers
10172     Louisville  ...       Chairs

                                            Product Name    Sales Quantity  \
5                Global Deluxe High-Back Manager's Chair  2573.82        9
30                 Tennsco 6- and 18-Compartment Lockers  1325.85        5
43     Hon 4700 Series Mobuis Mid-Back Task Chairs wi...  1067.94        3
102              Hon 2111 Invitation Series Corner Table  1256.22        6
181    Global Commerce Series High-Back Swivel/Tilt C...  1139.92        4
...                                                  ...      ...      ...
10059                                   Letter Size Cart  1000.02        7
10066                             Hon GuestStacker Chair  1586.69        7
10120  Office Impressions Heavy Duty Welded Shelving ...  1003.62        6
10121               Hewlett Packard LaserJet 3310 Copier  2879.95        6
10172  DMI Arturo Collection Mission-style Design Woo...  1207.84        8

      Discount     Profit   Profit Status  Discount Percentage  Order Year  \
5          0.0   746.4078          Profit                    0        2023
30         0.0   238.6530          Profit                    0        2023
43         0.0   224.2674          Profit                    0        2023
102        0.0    75.3732          Profit                    0        2023
181        0.0   284.9800          Profit                    0        2023
...        ...        ...             ...                  ...         ...
10059      0.0   290.0058          Profit                    0        2026
10066      0.0   412.5394          Profit                    0        2026
10120      0.0     0.0000  No Profit Loss                    0        2026
10121      0.2  1007.9832          Profit                   20        2026
10172      0.0   314.0384          Profit                    0        2026

       Order Month
5          January
30         January
43         January
102       February
181          March
...            ...
10059     December
10066     December
10120     December
10121     December
10172     December

[470 rows x 25 columns]

### Q19. Display all Records where Discount is greater than 20%.

In [28]:
records=df[df["Discount Percentage"]>20]
print(records)

       Row ID        Order ID Order Date  Ship Date       Ship Mode  \
1           2  US-2023-112326 2023-01-04 2023-01-08  Standard Class
14         15  US-2023-105417 2023-01-07 2023-01-12  Standard Class
15         16  US-2023-105417 2023-01-07 2023-01-12  Standard Class
24         25  US-2023-118192 2023-01-13 2023-01-18  Standard Class
32         33  US-2023-149524 2023-01-14 2023-01-15     First Class
...       ...             ...        ...        ...             ...
10154   10155  US-2026-163860 2026-12-28 2027-01-01  Standard Class
10156   10157  US-2026-163860 2026-12-28 2027-01-01  Standard Class
10157   10158  US-2026-163860 2026-12-28 2027-01-01  Standard Class
10161   10162  US-2026-162068 2026-12-28 2026-12-31    Second Class
10162   10163  US-2026-163860 2026-12-28 2027-01-01  Standard Class

      Customer ID     Customer Name      Segment Country/Region          City  \
1        PO-19195     Phillina Ober  Home Office  United States    Naperville
14       VS-21820  Vivek Sundaresam     Consumer  United States    Huntsville
15       VS-21820  Vivek Sundaresam     Consumer  United States    Huntsville
24       MM-17920     Michael Moore     Consumer  United States        Newark
32       BS-11590     Brendan Sweed    Corporate  United States  Philadelphia
...           ...               ...          ...            ...           ...
10154    LO-17170        Lori Olson    Corporate  United States        Peoria
10156    LO-17170        Lori Olson    Corporate  United States        Peoria
10157    LO-17170        Lori Olson    Corporate  United States        Peoria
10161    PC-18745    Pamela Coakley    Corporate  United States      Loveland
10162    LO-17170        Lori Olson    Corporate  United States        Peoria

       ... Sub-Category                                       Product Name  \
1      ...      Binders         GBC Standard Plastic Binding Systems Combs
14     ...  Furnishings  Howard Miller 14-1/2" Diameter Chrome Round Wa...
15     ...      Binders  Acco Four Pocket Poly Ring Binder with Label H...
24     ...      Binders                        Avery Metallic Poly Binders
32     ...    Bookcases              Sauder Cornerstone Collection Library
...    ...          ...                                                ...
10154  ...       Chairs             Padded Folding Chairs, Black, 4/Carton
10156  ...  Furnishings                   3M Hangers With Command Adhesive
10157  ...  Furnishings  G.E. Longer-Life Indoor Recessed Floodlight Bulbs
10161  ...      Binders          Avery Reinforcements for Hole-Punch Pages
10162  ...      Binders                       Computer Printout Index Tabs

        Sales Quantity Discount   Profit Profit Status  Discount Percentage  \
1        3.54        2      0.8  -5.4870          Loss                   80
14      76.73        3      0.6 -53.7096          Loss                   60
15      10.43        7      0.8 -18.2525          Loss                   80
24       3.44        2      0.7  -2.5212          Loss                   70
32      61.96        4      0.5 -53.2856          Loss                   50
...       ...      ...      ...      ...           ...                  ...
10154  113.37        2      0.3  -3.2392          Loss                   30
10156    2.96        2      0.6  -1.4060          Loss                   60
10157    7.97        3      0.6  -2.3904          Loss                   60
10161    1.19        2      0.7  -0.9900          Loss                   70
10162    1.68        5      0.8  -2.6880          Loss                   80

       Order Year  Order Month
1            2023      January
14           2023      January
15           2023      January
24           2023      January
32           2023      January
...           ...          ...
10154        2026     December
10156        2026     December
10157        2026     December
10161        2026     December
10162        2026     December

[1415 rows x 25 columns]

### Q20. Display all records with  Profit  Status (Loss).

In [29]:
df[df["Profit Status"]=="Loss"]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Profit Status,Discount Percentage,Order Year,Order Month
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Binders,GBC Standard Plastic Binding Systems Combs,3.54,2,0.8,-5.4870,Loss,80,2023,January
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Storage,SAFCO Boltless Steel Shelving,272.74,3,0.2,-64.7748,Loss,20,2023,January
14,15,US-2023-105417,2023-01-07,2023-01-12,Standard Class,VS-21820,Vivek Sundaresam,Consumer,United States,Huntsville,...,Furnishings,"Howard Miller 14-1/2"" Diameter Chrome Round Wa...",76.73,3,0.6,-53.7096,Loss,60,2023,January
15,16,US-2023-105417,2023-01-07,2023-01-12,Standard Class,VS-21820,Vivek Sundaresam,Consumer,United States,Huntsville,...,Binders,Acco Four Pocket Poly Ring Binder with Label H...,10.43,7,0.8,-18.2525,Loss,80,2023,January
24,25,US-2023-118192,2023-01-13,2023-01-18,Standard Class,MM-17920,Michael Moore,Consumer,United States,Newark,...,Binders,Avery Metallic Poly Binders,3.44,2,0.7,-2.5212,Loss,70,2023,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10162,10163,US-2026-163860,2026-12-28,2027-01-01,Standard Class,LO-17170,Lori Olson,Corporate,United States,Peoria,...,Binders,Computer Printout Index Tabs,1.68,5,0.8,-2.6880,Loss,80,2026,December
10167,10168,US-2026-127516,2026-12-28,2027-01-03,Standard Class,EH-14005,Erica Hernandez,Home Office,United States,Nashville,...,Storage,Carina Double Wide Media Storage Towers in Nat...,64.78,1,0.2,-12.9568,Loss,20,2026,December
10173,10174,US-2026-118885,2026-12-29,2027-01-02,Standard Class,JG-15160,James Galang,Consumer,United States,Los Angeles,...,Chairs,"Global High-Back Leather Tilter, Burgundy",393.57,4,0.2,-44.2764,Loss,20,2026,December
10191,10192,US-2026-156720,2026-12-30,2027-01-03,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,Fasteners,Bagged Rubber Bands,3.02,3,0.2,-0.6048,Loss,20,2026,December
10193,10194,CA-2026-143500,2026-12-30,2027-01-03,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,Binders,Wilson Jones Impact Binders,3.02,3,0.2,-0.6048,Loss,20,2026,December

### Q21. Display all Records from a Specific Cities.

In [30]:
df[df["City"].isin(["Los Angeles","Peoria"])]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Profit Status,Discount Percentage,Order Year,Order Month
11,12,US-2023-130813,2023-01-06,2023-01-08,Second Class,LS-17230,Lycoris Saunders,Consumer,United States,Los Angeles,...,Paper,Xerox 225,19.44,3,0.0,9.3312,Profit,0,2023,January
47,48,US-2023-148614,2023-01-20,2023-01-25,Standard Class,MV-17485,Mark Van Huff,Consumer,United States,Los Angeles,...,Furnishings,"Eldon Expressions Desk Accessory, Wood Pencil ...",19.30,2,0.0,5.7900,Profit,0,2023,January
56,57,US-2023-148614,2023-01-20,2023-01-25,Standard Class,MV-17485,Mark Van Huff,Consumer,United States,Los Angeles,...,Paper,"Wirebound Service Call Books, 5 1/2"" x 4""",19.36,2,0.0,9.2928,Profit,0,2023,January
121,122,US-2023-164903,2023-02-20,2023-02-24,Standard Class,SR-20740,Steven Roelle,Home Office,United States,Los Angeles,...,Paper,Xerox 204,12.96,2,0.0,6.2208,Profit,0,2023,February
252,253,US-2023-120838,2023-03-23,2023-03-26,Second Class,PO-18865,Patrick O'Donnell,Consumer,United States,Los Angeles,...,Storage,Economy Rollaway Files,330.40,2,0.0,85.9040,Profit,0,2023,March
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10156,10157,US-2026-163860,2026-12-28,2027-01-01,Standard Class,LO-17170,Lori Olson,Corporate,United States,Peoria,...,Furnishings,3M Hangers With Command Adhesive,2.96,2,0.6,-1.4060,Loss,60,2026,December
10157,10158,US-2026-163860,2026-12-28,2027-01-01,Standard Class,LO-17170,Lori Olson,Corporate,United States,Peoria,...,Furnishings,G.E. Longer-Life Indoor Recessed Floodlight Bulbs,7.97,3,0.6,-2.3904,Loss,60,2026,December
10162,10163,US-2026-163860,2026-12-28,2027-01-01,Standard Class,LO-17170,Lori Olson,Corporate,United States,Peoria,...,Binders,Computer Printout Index Tabs,1.68,5,0.8,-2.6880,Loss,80,2026,December
10173,10174,US-2026-118885,2026-12-29,2027-01-02,Standard Class,JG-15160,James Galang,Consumer,United States,Los Angeles,...,Chairs,"Global High-Back Leather Tilter, Burgundy",393.57,4,0.2,-44.2764,Loss,20,2026,December
10182,10183,US-2026-118885,2026-12-29,2027-01-02,Standard Class,JG-15160,James Galang,Consumer,United States,Los Angeles,...,Phones,Adtran 1202752G1,302.38,3,0.2,22.6782,Profit,20,2026,December

### Q22. Display all Orders placed in January.

In [31]:
Jan_orders=df[df["Order Month"]=="January"]
print(Jan_orders)

      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
0          1  US-2023-103800 2023-01-03 2023-01-07  Standard Class
1          2  US-2023-112326 2023-01-04 2023-01-08  Standard Class
2          3  US-2023-112326 2023-01-04 2023-01-08  Standard Class
3          4  US-2023-112326 2023-01-04 2023-01-08  Standard Class
4          5  US-2023-141817 2023-01-05 2023-01-12  Standard Class
...      ...             ...        ...        ...             ...
6971    6972  US-2026-164329 2026-01-30 2026-01-30        Same Day
6972    6973  US-2026-121790 2026-01-30 2026-02-06  Standard Class
6973    6974  US-2026-157273 2026-01-30 2026-02-02     First Class
6974    6975  US-2026-121790 2026-01-30 2026-02-06  Standard Class
6975    6976  US-2026-104220 2026-01-30 2026-02-05  Standard Class

     Customer ID    Customer Name      Segment Country/Region           City  \
0       DP-13000    Darren Powers     Consumer  United States        Houston
1       PO-19195    Phillina Ober  Home Office  United States     Naperville
2       PO-19195    Phillina Ober  Home Office  United States     Naperville
3       PO-19195    Phillina Ober  Home Office  United States     Naperville
4       MB-18085       Mick Brown     Consumer  United States   Philadelphia
...          ...              ...          ...            ...            ...
6971    MM-17920    Michael Moore     Consumer  United States  San Francisco
6972    LP-17095        Liz Preis     Consumer  United States         Aurora
6973    SZ-20035       Sam Zeldin  Home Office  United States        Seattle
6974    LP-17095        Liz Preis     Consumer  United States         Aurora
6975    BV-11245  Benjamin Venier    Corporate  United States     Des Moines

      ... Sub-Category                                       Product Name  \
0     ...        Paper  Message Book, Wirebound, Four 5 1/2" X 4" Form...
1     ...      Binders         GBC Standard Plastic Binding Systems Combs
2     ...       Labels                                          Avery 508
3     ...      Storage                      SAFCO Boltless Steel Shelving
4     ...          Art  Avery Hi-Liter EverBold Pen Style Fluorescent ...
...   ...          ...                                                ...
6971  ...      Storage          Space Solutions Commercial Steel Shelving
6972  ...     Supplies  Acme Tagit Stainless Steel Antibacterial Scissors
6973  ...       Phones                     Mitel 5320 IP Phone VoIP phone
6974  ...       Phones                                  Samsung Galaxy S4
6975  ...       Phones                                  AT&T 841000 Phone

        Sales Quantity Discount    Profit Profit Status  Discount Percentage  \
0       16.45        2      0.2    5.5512        Profit                   20
1        3.54        2      0.8   -5.4870          Loss                   80
2       11.78        3      0.2    4.2717        Profit                   20
3      272.74        3      0.2  -64.7748          Loss                   20
4       19.54        3      0.2    4.8840        Profit                   20
...       ...      ...      ...       ...           ...                  ...
6971   129.30        2      0.0    6.4650        Profit                    0
6972    31.68        4      0.2    2.7720        Profit                   20
6973   604.77        4      0.2   60.4768        Profit                   20
6974  2003.17        4      0.2  250.3960        Profit                   20
6975   207.00        3      0.0   51.7500        Profit                    0

      Order Year  Order Month
0           2023      January
1           2023      January
2           2023      January
3           2023      January
4           2023      January
...          ...          ...
6971        2026      January
6972        2026      January
6973        2026      January
6974        2026      January
6975        2026      January

[404 rows x 25 columns]

### Q23. Display the Top 10 Highest Sales Records.

In [32]:
Top10_sales=df.sort_values(by="Sales",ascending=False).head(10)

print(Top10_sales)

      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
226      227  US-2023-145317 2023-03-18 2023-03-23  Standard Class
5894    5895  US-2025-118689 2025-10-02 2025-10-09  Standard Class
7255    7256  US-2026-140151 2026-03-23 2026-03-25     First Class
9171    9172  US-2026-127180 2026-10-22 2026-10-24     First Class
9517    9518  US-2026-166709 2026-11-17 2026-11-22  Standard Class
6674    6675  US-2025-117121 2025-12-17 2025-12-21  Standard Class
1203    1204  US-2023-116904 2023-09-23 2023-09-28  Standard Class
4624    4625  US-2025-107440 2025-04-16 2025-04-20  Standard Class
4282    4283  US-2025-158841 2025-02-02 2025-02-04    Second Class
4845    4846  US-2025-143714 2025-05-23 2025-05-27  Standard Class

     Customer ID       Customer Name      Segment Country/Region  \
226     SM-20320         Sean Miller  Home Office  United States
5894    TC-20980        Tamara Chand    Corporate  United States
7255    RB-19360        Raymond Buch     Consumer  United States
9171    TA-21385        Tom Ashbrook  Home Office  United States
9517    HL-15040        Hunter Lopez     Consumer  United States
6674    AB-10105       Adrian Barton     Consumer  United States
1203    SC-20095        Sanjit Chand     Consumer  United States
4624    BS-11365        Bill Shonely    Corporate  United States
4282    SE-20110        Sanjit Engle     Consumer  United States
4845    CC-12370  Christopher Conant     Consumer  United States

               City  ... Sub-Category  \
226    Jacksonville  ...     Machines
5894      Lafayette  ...      Copiers
7255        Seattle  ...      Copiers
9171  New York City  ...      Copiers
9517         Newark  ...      Copiers
6674        Detroit  ...      Binders
1203    Minneapolis  ...      Binders
4624       Lakewood  ...     Machines
4282      Arlington  ...     Machines
4845   Philadelphia  ...      Copiers

                                           Product Name     Sales Quantity  \
226   Cisco TelePresence System EX90 Videoconferenci...  22638.48        6
5894              Canon imageCLASS 2200 Advanced Copier  17499.95        5
7255              Canon imageCLASS 2200 Advanced Copier  13999.96        4
9171              Canon imageCLASS 2200 Advanced Copier  11199.97        4
9517              Canon imageCLASS 2200 Advanced Copier  10499.97        3
6674   GBC Ibimaster 500 Manual ProClick Binding System   9892.74       13
1203               Ibico EPK-21 Electric Binding System   9449.95        5
4624   3D Systems Cube Printer, 2nd Generation, Magenta   9099.93        7
4282  HP Designjet T520 Inkjet Large Format Printer ...   8749.95        5
4845              Canon imageCLASS 2200 Advanced Copier   8399.98        4

     Discount     Profit Profit Status  Discount Percentage  Order Year  \
226       0.5 -1811.0784          Loss                   50        2023
5894      0.0  8399.9760        Profit                    0        2025
7255      0.0  6719.9808        Profit                    0        2026
9171      0.2  3919.9888        Profit                   20        2026
9517      0.0  5039.9856        Profit                    0        2026
6674      0.0  4946.3700        Profit                    0        2025
1203      0.0  4630.4755        Profit                    0        2023
4624      0.0  2365.9818        Profit                    0        2025
4282      0.0  2799.9840        Profit                    0        2025
4845      0.4  1119.9968        Profit                   40        2025

      Order Month
226         March
5894      October
7255        March
9171      October
9517     November
6674     December
1203    September
4624        April
4282     February
4845          May

[10 rows x 25 columns]

# Level 4: GroupBy & Business Analysis

### Q24. Calculate Category-wise Total Sales.

In [33]:
df.groupby("Category",as_index=False)["Sales"].sum()

          Category      Sales
0        Furniture  754747.69
1  Office Supplies  731893.14
2       Technology  839893.27

###  Q25. Calculate Category-wise Total Profit.

In [34]:
df.groupby("Category",as_index=False)["Profit"].sum()

          Category       Profit
0        Furniture   19729.9956
1  Office Supplies  126023.4434
2       Technology  146543.3756

### Q26. Calculate Region-wise Total Sales.

In [35]:
df.groupby("Region",as_index=False)["Sales"].sum()

    Region      Sales
0  Central  503170.54
1     East  691828.19
2    South  391721.83
3     West  739813.54

### Q27. Calculate Segment-wise Average Sales.

In [36]:
df.groupby("Segment",as_index=False)["Profit"].mean()

       Segment     Profit
0     Consumer  25.823035
1    Corporate  30.501502
2  Home Office  33.831996

### Q28. Calculate Ship Mode-wise Order Count.

In [37]:
df.groupby("Ship Mode").count()

,Row ID,Order ID,Order Date,Ship Date,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Profit Status,Discount Percentage,Order Year,Order Month
Ship Mode,,,,,,,,,,,,,,,,,,,,,
First Class,1548,1548,1548,1548,1548,1548,1548,1548,1548,1548,...,1548,1548,1548,1548,1548,1548,1548,1548,1548,1548
Same Day,547,547,547,547,547,547,547,547,547,547,...,547,547,547,547,547,547,547,547,547,547
Second Class,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,...,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979
Standard Class,6120,6120,6120,6120,6120,6120,6120,6120,6120,6120,...,6120,6120,6120,6120,6120,6120,6120,6120,6120,6120

### Q29. Count the Number of Orders Placed by Each Customer.

In [38]:
df["Customer Name"].value_counts()

Customer Name
William Brown        41
Ben Ferrer           37
Greg Guthrie         36
Xylona Preis         34
Jane Waco            34
                     ..
Ricardo Emerson       1
Lela Donovan          1
Anthony O'Donnell     1
Carl Jackson          1
Jocasta Rupert        1
Name: count, Length: 800, dtype: int64

### Q30. Display the Top 10 Customers based on Total Sales.

In [39]:
customer_sales=df.groupby("Customer Name",as_index=False)["Sales"].sum()
customer_sales.sort_values(by="Sales",ascending=False,ignore_index=True).head(10)

        Customer Name     Sales
0         Sean Miller  25043.07
1        Tamara Chand  19052.22
2        Raymond Buch  15117.35
3        Tom Ashbrook  14595.62
4       Adrian Barton  14473.56
5        Ken Lonsdale  14175.22
6        Sanjit Chand  14142.34
7        Hunter Lopez  12873.30
8        Sanjit Engle  12209.44
9  Christopher Conant  12129.08

### Q31.  Identify the Top 10 Products with the Highest Total Profit.

In [40]:
product_profit=df.groupby("Product Name",as_index=False)["Profit"].sum()
product_profit.sort_values(by="Profit",ascending=False,ignore_index=True).head(10)

                                        Product Name      Profit
0              Canon imageCLASS 2200 Advanced Copier  25199.9280
1  Fellowes PB500 Electric Punch Plastic Comb Bin...   7753.0390
2               Hewlett Packard LaserJet 3310 Copier   6983.8836
3                 Canon PC1060 Personal Laser Copier   4570.9347
4  HP Designjet T520 Inkjet Large Format Printer ...   4094.9766
5                  Ativa V4110MDD Micro-Cut Shredder   3772.9461
6   3D Systems Cube Printer, 2nd Generation, Magenta   3717.9714
7  Plantronics Savi W720 Multi-Device Wireless He...   3696.2820
8               Ibico EPK-21 Electric Binding System   3345.2823
9                  Zebra ZM400 Thermal Label Printer   3343.5360

### Q32. Analyze Year-wise Total Sales.

In [41]:
df.groupby("Order Year",as_index=False)["Sales"].sum()

   Order Year      Sales
0        2023  494040.18
1        2024  472992.91
2        2025  613933.71
3        2026  745567.30

# Level 5: Pivot Table Analysis

### Q33. Create a Pivot Table to display Category-wise Total Sales across Regions.

In [42]:
Category_Region_Sales = pd.pivot_table(
    df,
    index="Category",
    columns="Region",
    values="Sales",
    aggfunc="sum",
    fill_value=0
)

print(Category_Region_Sales)

Region             Central       East      South       West
Category
Furniture        164537.63  212231.63  117298.68  260679.75
Office Supplies  168216.62  211658.46  125651.26  226366.80
Technology       170416.29  267938.10  148771.89  252766.99

### Q34. Create a Pivot Table to display Category-wise Total Sales across Segments.

In [43]:
Category_Seg_Sales = pd.pivot_table(
    df,
    index="Category",
    columns="Segment",
    values="Sales",
    aggfunc="sum",
    fill_value=0

)

print(Category_Seg_Sales )

Segment           Consumer  Corporate  Home Office
Category
Furniture        394723.67  231267.53    128756.49
Office Supplies  369535.97  236313.67    126043.50
Technology       406399.89  248224.88    185268.50

### Q35. Create a Pivot Table to display Sub-Category-wise Total Sales across Regions.

In [44]:
SubCategory_Sales = pd.pivot_table(
    df,
    index="Sub-Category",
    columns="Region",
    values="Sales",
    aggfunc="sum",
    fill_value=0

)

print(SubCategory_Sales )

Region         Central       East     South       West
Sub-Category
Accessories   33956.08   45033.38  27276.75   61114.10
Appliances    23581.98   34789.90  19525.34   30315.94
Art            5765.32    7917.58   4655.65    9320.45
Binders       58060.76   56302.69  37030.29   55961.07
Bookcases     24157.16   43963.91  10899.37   36340.74
Chairs        85941.17   97515.63  45176.44  107135.01
Copiers       37259.57   54436.72   9299.75   49749.23
Envelopes      4636.85    4375.88   3345.55    4170.06
Fasteners       778.02    1112.82    503.31    6138.06
Furnishings   15284.34   30825.93  17306.68   32181.13
Labels         2451.48    2811.65   2353.18    5078.72
Machines      26797.38   66106.15  53890.96   43130.51
Paper         17491.91   21175.14  14150.98   26722.54
Phones        72403.26  102361.85  58304.43   98773.15
Storage       45982.93   72360.74  35768.03   70532.84
Supplies       9467.37   10812.06   8318.93   18127.12
Tables        39154.96   39926.16  43916.19   85022.87

### Q36.  Create a Pivot Table to display Region-wise Average Discount.

In [45]:
region_Avg_Dis = pd.pivot_table(
    df,
    index="Region",
    values="Discount",
    aggfunc="mean",
    fill_value=0
)

print(region_Avg_Dis)

         Discount
Region
Central  0.241002
East     0.143436
South    0.147253
West     0.108946

### Q37.  Create a Pivot Table to display Ship Mode-wise Order Count across Categories.

In [46]:
ship_mode_category = pd.pivot_table(
    df,
    index="Ship Mode",
    columns="Category",
    values="Order ID",
    aggfunc="count",
    fill_value=0
)

print(ship_mode_category)

Category        Furniture  Office Supplies  Technology
Ship Mode
First Class           329              918         301
Same Day              119              326         102
Second Class          439             1174         366
Standard Class       1314             3710        1096

# Level 6: Date Analysis

### Q38.  Calculate Delivery Days (Ship Date − Order Date).

In [47]:
df["Delivery Days"]=df["Ship Date"]-df["Order Date"]

In [48]:
df["Delivery Days"]

0       4 days
1       4 days
2       4 days
3       4 days
4       7 days
         ...
10189   4 days
10190   4 days
10191   4 days
10192   4 days
10193   4 days
Name: Delivery Days, Length: 10194, dtype: timedelta64[us]

### Q39. Identify the Month with the Highest Sales.

In [49]:
sales_month=pd.pivot_table(
    df,
    index="Order Month",
    values="Sales",
    aggfunc="sum",
)
highsales_month=sales_month.sort_values(by="Sales",ascending=False).head(1)
print(highsales_month)

                 Sales
Order Month
November     352665.95

### Q40. Identify the Year with the Highest Total Profit.

In [50]:
profit_year=pd.pivot_table(
    df,
    index="Order Year",
    values="Profit",
    aggfunc="sum",
)
highprofit_year=profit_year.sort_values(by="Profit",ascending=False).head(1)
print(highprofit_year)

                Profit
Order Year
2026        95926.3476

# Business Insights

### Q41. Find the Top 3 Customers from each Region based on Total Sales.

In [51]:
top3_customers = (
    df.groupby(["Region", "Customer Name"], as_index=False)["Sales"]
      .sum()
)

top3_customers = (
    top3_customers
    .sort_values(["Region", "Sales"], ascending=[True, False])
    .groupby("Region")
    .head(3)
)

print(top3_customers)

       Region   Customer Name     Sales
579   Central    Tamara Chand  18437.14
5     Central   Adrian Barton  12181.60
57    Central    Becky Martin  10539.90
1283     East    Tom Ashbrook  13723.50
918      East    Hunter Lopez  10522.55
705      East    Bill Shonely  10022.29
1752    South     Sean Miller  23669.21
1743    South    Sanjit Engle   8805.04
1506    South  Grant Thornton   8167.42
2361     West    Raymond Buch  14345.28
2206     West    Ken Lonsdale   8472.39
2086     West    Greg Guthrie   8154.48

### Q42. Calculate the Running Total of Sales.

In [52]:
df = df.sort_values("Order Date")

df["Running Total Sales"] = df["Sales"].cumsum()

print(df[["Order Date", "Sales", "Running Total Sales"]])

      Order Date   Sales  Running Total Sales
0     2023-01-03   16.45                16.45
1     2023-01-04    3.54                19.99
2     2023-01-04   11.78                31.77
3     2023-01-04  272.74               304.51
4     2023-01-05   19.54               324.05
...          ...     ...                  ...
10188 2026-12-30   13.90           2326454.56
10189 2026-12-30   52.78           2326507.34
10190 2026-12-30   20.72           2326528.06
10191 2026-12-30    3.02           2326531.08
10193 2026-12-30    3.02           2326534.10

[10194 rows x 3 columns]

### Q43. Rank Sub Category based on Total Sales.

In [53]:

Subcategory_sales = (
    df.groupby("Sub-Category",as_index=False )["Sales"]
      .sum()
)

Subcategory_sales["Rank"]=Subcategory_sales["Sales"].rank(
    method="dense",
    ascending=False)
Subcategory_sales=Subcategory_sales.sort_values(by="Rank",ignore_index=True)
print(Subcategory_sales)

   Sub-Category      Sales  Rank
0        Chairs  335768.25   1.0
1        Phones  331842.69   2.0
2       Storage  224644.54   3.0
3        Tables  208020.18   4.0
4       Binders  207354.81   5.0
5      Machines  189925.00   6.0
6   Accessories  167380.31   7.0
7       Copiers  150745.27   8.0
8     Bookcases  115361.18   9.0
9    Appliances  108213.16  10.0
10  Furnishings   95598.08  11.0
11        Paper   79540.57  12.0
12     Supplies   46725.48  13.0
13          Art   27659.00  14.0
14    Envelopes   16528.34  15.0
15       Labels   12695.03  16.0
16    Fasteners    8532.21  17.0

### Q44. Calculate the Percentage Contribution of Each Segment to Total Profit.

In [54]:
segment_profit=df.groupby("Segment",as_index=False)["Profit"].sum()
total_profit=segment_profit["Profit"].sum()
segment_profit["Contribution (%)"]=(segment_profit["Profit"]/total_profit)*100
print(segment_profit)

       Segment       Profit  Contribution (%)
0     Consumer  136371.4463         46.655126
1    Corporate   94249.6400         32.244498
2  Home Office   61675.7283         21.100376

### Q45. Find the Most Frequently Ordered Product.

In [55]:
df["Product Name"].value_counts().head(1)

Product Name
Staples    50
Name: count, dtype: int64

### Q46.Find the Customer Retention Rate (if multiple years are available).

In [56]:
customer_year = (
    df.groupby("Customer Name")["Order Year"]
      .nunique()
      .reset_index()
)

retained_customers = customer_year[customer_year["Order Year"] > 1]

print(retained_customers)

          Customer Name  Order Year
0         Aaron Bergman           2
1         Aaron Hawkins           4
2        Aaron Smayling           3
3       Adam Bellavance           3
4             Adam Hart           4
..                  ...         ...
795        Xylona Preis           4
796       Yana Sorensen           2
797      Yoseph Carroll           4
798    Zuschuss Carroll           4
799  Zuschuss Donatelli           3

[779 rows x 2 columns]

### Q47. Calculate the Profit Margin (%) for each Order.

In [57]:
df["Profit Margin"]=(df["Profit"]/df["Sales"])*100
df["Profit Margin"].round(2)

0         33.75
1       -155.00
2         36.26
3        -23.75
4         24.99
          ...
10188     32.51
10189     37.50
10190     31.25
10191    -20.03
10193    -20.03
Name: Profit Margin, Length: 10194, dtype: float64

### Q48. Find the Best Performing State based on Total Sales.

In [58]:
best_states = (
    df.groupby("City", as_index=False)["Sales"]
      .sum()
      .sort_values(by="Sales", ascending=False)
      .head(10)
)

print(best_states)

              City      Sales
335  New York City  256368.12
270    Los Angeles  175851.30
460        Seattle  119540.74
446  San Francisco  112669.07
380   Philadelphia  109077.05
211        Houston   64504.70
82         Chicago   48539.56
445      San Diego   47521.05
220   Jacksonville   44713.17
472    Springfield   43054.34

# Conclusion

In this project I performed:

- Data Cleaning
- Missing Value Handling
- Feature Engineering
- Filtering
- GroupBy Analysis
- Pivot Table
- Date Analysis
- Business Insights

Libraries Used

- Pandas
- NumPy